# Loap default processing options
imports:
  #- { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
  - { resource: "EXT:tmpl/Configuration/RTE/Editor/Processing.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }
  # Import Custom Plugins / Configs
  - { resource: "EXT:tmpl/Configuration/RTE/Editor/Plugins.yaml" }
  - { resource: "EXT:tmpl/Configuration/RTE/Editor/Base.yaml" }
  # - { resource: "EXT:tmpl/Configuration/RTE/Editor/ButtonClasses.yaml" }
  # Import the image plugin configuration
  - { resource: "EXT:rte_ckeditor_image/Configuration/RTE/Plugin.yaml" }


#contentsCss: ["EXT:mhr/Resources/Public/Stylesheets/rte.css"]

# Minimal configuration for the editor
editor:
  contentsCss: "/assets/src/css/rte.css"

  config:

    allowedContent: true

    format_tags: "div;p;h2;h3;h4;h5"

    toolbarGroups:
      - { name: 'styles', groups: [ 'styles' ] }
      - '/'
      - { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] }
      - { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] }
      - { name: 'insert', groups: [ 'insert' ] }
      - { name: 'links', groups: [ 'links' ] }
      - { name: 'document', groups: [ 'mode', 'document', 'doctools' ] }
      - { name: 'clipboard', groups: [ 'clipboard', 'undo' ] }
      - { name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] }
      - { name: 'forms', groups: [ 'forms' ] }
      - { name: 'colors', groups: [ 'colors' ] }
      - { name: 'tools', groups: [ 'tools' ] }
      - { name: 'others', groups: [ 'others' ] }
      - { name: 'about', groups: [ 'about' ] }

    justifyClasses:
      - text-left
      - text-center
      - text-right
      - text-justify

    extraPlugins:
      - justify

    removeButtons:
      - About
      - Maximize
      - ShowBlocks
      - BGColor
      - TextColor
      - Iframe
      - FontSize
      - Flash
      - HorizontalRule
      - Smiley
      - PageBreak
      - Anchor
      - BidiLtr
      - BidiRtl
      - Language
      - JustifyBlock
      - Blockquote
      - CreateDiv
      - Underline
      - Strike
      - HiddenField
      - ImageButton
      - Button
      - Select
      - Textarea
      - TextField
      - Radio
      - Checkbox
      - Form
      - SelectAll
      - Find
      - Replace
      - Cut
      - Copy
      - Paste
      - PasteText
      - PasteFromWord
      - Templates
      - Save
      - NewPage
      - Preview
      - Print

    # Limit the height of the editor
    height: 350
